import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-auto mt-20 max-w-4xl">
        <h1 className="text-center text-7xl font-bold">
          <span className="mr-4">Welcome to</span>
          <a href="https://nextjs.org" className="text-blue-700 hover:text-blue-500">
            Next.js!
          </a>
        </h1>
      </main>
    </>
  );
};

export default Home;
