import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>MOZABRICK-clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-auto mt-20 max-w-4xl">
        <h1 className="text-center text-5xl font-bold">
          <span className="mr-3">Welcome to</span>

          <a
            href="https://github.com/denis-avakov/mozabrick-clone"
            className="text-blue-700 hover:text-blue-500"
          >
            MOZABRICK-clone
          </a>
        </h1>
      </main>
    </>
  );
};

export default Home;
